//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftWareEmployee
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public Nullable<decimal> EmpSalary { get; set; }
        public Nullable<System.DateTime> EmpDOB { get; set; }
        public string EmpAddress { get; set; }
        public string EmpStatus { get; set; }
    }
}
